### ISSUE TITLE
Scroll Issue with page links in footer 

### ISSUE THREAD

**Issue by pvgupta24** [woc-nitk/woc-nitk.github.io#18]
On mobile devices, when a link in the footer is clicked like /projects or /orgs, move focus to the top of the page. Focus stays at the footer which doesn't indicate whether the new page is loaded or not :P 

@adharshkamath @Z0Marlin @Sriram2001

**Comment by Sriram2001** [comment]
Fixed with https://github.com/woc-nitk/woc-nitk.github.io/commit/08cb6703032c2c475626fe5ff9e395b33da468af.
Closing the issue.
